### ISSUE TITLE
bug: edge case where duplicates end up in rendered `atlantis.yaml`

### ISSUE THREAD

**Issue by 3bbbeau** [3bbbeau/tfvars-atlantis-config#3]
Through using this tool on large repos, I've found an edge case where duplicates can end up in `atlantis.yaml`.

Will put in some logic to fix it, and address the need to add tests to to `generate` cmd.

## Example
```yaml
- name: my-terraform
  dir: service/my-terraform
  workspace: dev
- name: my-terraform
  dir: service/my-terraform
  workspace: dev
```

## Result
>_parsing atlantis.yaml: found two or more projects with name "service-my-terraform-dev"; project names must be unique_
